import Head from "next/head";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Airbnb-clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex justify-center items-center">
				<h1>Cracking Airbnb</h1>
			</div>
		</div>
	);
}
